### ISSUE TITLE
Problem Mounting Existing Bucket

### ISSUE THREAD

**Issue by iwalmsley** [IBM/dataset-lifecycle-framework#34]
Hi there,

Thanks for the efforts, finding this project very useful. One issue i'm having however (apologies if it's obvious) is mounting an existing bucket, even though I am specifying the bucket in the secret e.g this is for a non-AWS s3 endpoint;

```
apiVersion: v1
data:
  accessKeyID: accessKey
  bucket: bucket
  endpoint: endpoint
  region: ""
  secretAccessKey: secretAccessKey
kind: Secret
metadata:
  name: csi-s3-pvc
  namespace: test-namespace
type: Opaque
```

Rather than mounting the specified bucket, it instead generates a new bucket with the name of the Kubernetes pvc. Just want to confirm that I am doing things correctly and if not what I need to change?

Versions:
Attacher: 2.2.0
Provisioner: 1.6.0

**Comment by YiannisGkoufas** [comment]
Hi @iwalmsley thanks a lot for your kind words!
Instead of creating a Secret like you are showing, you need to create a Dataset like that:
```
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: your-dataset
spec:
  local:
    type: "COS"
    accessKeyID: "XXXXXXX"
    secretAccessKey: "XXXXXX"
    endpoint: "https://MAKE_SURE_YOU_HAVE_HTTP_OR_HTTPS_IN_THE_URL"
    bucket: "bucket"
    region: ""
```
Also before you create the above dataset, that you delete the secrets, configmaps you created related to the above.
